### ISSUE TITLE
Error when trying to install Potassium

### ISSUE THREAD

**Issue by nv-vn** [IodineLang/Ion#1]
```
Collecting package definitions...
Found package potassium.
Confirm installation of packages: 
-----------------
Potassium (v0.1.0)
-----------------
Any packages containing @ have multiple repository definitions, and are using the named repository.

Packages will be installed to: /home/nv/.ion
Is this ok? (y/n)
Installing Potassium from https://github.com/IodineLang/Potassium/archive/master.zip...
Unzipping /home/nv/.ion/potassium.zip to /home/nv/.ion/potassium...
An unhandled InternalErrorException has occured!
	Message: Internal exception: The requested feature is not implemented.
 Inner Exception: 

Stack trace:
------------
 at main (Module: main, Line: 1)
```

**Comment by Aurora0000** [comment]
Which commit of Ion are you using?

**Comment by Aurora0000** [comment]
Also, I believe I know what the issue is. Please type:

    mono --version

And share the output.

**Comment by nv-vn** [comment]
The most recent version. My Mono version is 3.2.8 (old, but it's what is distributed in Debian Stable).

**Comment by Aurora0000** [comment]
The issue is that the unzipping used by Ion requires .NET 4.5 (or Mono 4.0 or above). Please follow [these instructions] (http://www.mono-project.com/docs/getting-started/install/linux/#debian-ubuntu-and-derivatives) to update your Mono installation.

**Comment by nv-vn** [comment]
Alright, that seems to have fixed it. Thanks.

**Comment by Aurora0000** [comment]
Glad it helped, @nv-vn!
